name: "Unit Test: basic functions"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-basic-funcs:
    name: Test basic funcs on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Install poetry
        shell: bash
        run: pipx install poetry

      - name: Setup Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: "poetry"

      - name: Install dependencies
        shell: bash
        run: poetry install --with dev

      - name: Run unit tests
        shell: bash
        run: poetry run pytest unittest/test_avid.py unittest/test_file.py unittest/test_func.py

      - name: Upload log as artifact
        uses: actions/upload-artifact@v7
        if: ${{ always() }}
        with:
          name: JavSP-basic-funcs-${{ matrix.os }}.log
          path: javsp/JavSP.log
